<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- 继承父工程统一配置 -->
    <parent>
        <groupId>io.github.forgottenlab.emg</groupId>
        <artifactId>entity-model-generator</artifactId>
        <version>1.2.2</version>
    </parent>

    <artifactId>emg-core</artifactId>
    <name>EMG Core</name>
    <description>Core metadata, constants, and utility classes for Entity Model Generator.</description>

    <dependencies>
        <!--
            core 依赖 annotations：
            方便核心元数据、规则解析、常量定义等直接复用注解类型。
         -->
        <dependency>
            <groupId>io.github.forgottenlab.emg</groupId>
            <artifactId>emg-annotations</artifactId>
        </dependency>
    </dependencies>
</project>